
version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
        - mysql_db_data01:/var/lib/mysl
        - log_mysql:/var/log
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on: 
        - db
    image: wordpress:latest
    restart: always
    ports:
        - "8085:80"
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

volumes :
    mysql_db_data01: {}
    log_mysql: {}



